# Generated by Django 4.2.11 on 2024-05-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Green_World', '0002_favoriteplant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
