# Generated by Django 4.2.11 on 2024-05-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='common_name')),
                ('scientific_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/')),
                ('descriptions', models.TextField()),
                ('plant_origin', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Vegetables', 'Vegetables'), ('Leaf Plants', 'Leaf Plants'), ('Flowers', 'Flowers'), ('Fruits', 'Fruits'), ('Succulents', 'Succulents'), ('Weeds', 'Weeds'), ('Trees', 'Trees'), ('Toxic Plants', 'Toxic Plants')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'plant',
            },
        ),
        migrations.CreateModel(
            name='Scientific_Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plants_types')),
            ],
        ),
        migrations.CreateModel(
            name='Care_Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True, null=True)),
                ('watering_care', models.TextField(blank=True, null=True)),
                ('fertilizing_care', models.TextField(blank=True, null=True)),
                ('pruning', models.TextField(blank=True, null=True)),
                ('soil_care', models.TextField(blank=True, null=True)),
                ('sun_light', models.TextField(blank=True, null=True)),
                ('IdealTemperature', models.TextField(blank=True, null=True)),
                ('Propagation', models.TextField(blank=True, null=True)),
                ('TransplantingTime', models.TextField(blank=True, null=True)),
                ('PlantingTime', models.TextField(blank=True, null=True)),
                ('HarvestTime', models.TextField(blank=True, null=True)),
                ('plant_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plants_types')),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lifespan', models.CharField(blank=True, max_length=100, null=True)),
                ('Plant_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Planting_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Bloom_Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Harvest_Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Plant_Height', models.CharField(blank=True, max_length=100, null=True)),
                ('Spread', models.CharField(blank=True, max_length=50, null=True)),
                ('Flower_Size', models.CharField(blank=True, max_length=100, null=True)),
                ('Dormancy', models.CharField(blank=True, max_length=100, null=True)),
                ('Leaf_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Ideal_Temperature', models.CharField(blank=True, max_length=100, null=True)),
                ('Pollinators', models.CharField(blank=True, max_length=100, null=True)),
                ('Growth_Rate', models.CharField(blank=True, max_length=100, null=True)),
                ('Water', models.CharField(blank=True, max_length=100, null=True)),
                ('Sunlight', models.CharField(blank=True, max_length=100, null=True)),
                ('toxicity', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plants_types')),
            ],
        ),
    ]
