# Generated by Django 4.2.11 on 2024-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_categoryplant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryplant',
            name='name',
            field=models.CharField(blank=True, choices=[('Vegetables', 'Vegetables'), ('Leaf Plants', 'Leaf Plants'), ('Flowers', 'Flowers'), ('Fruits', 'Fruits'), ('Succulents', 'Succulents'), ('Weeds', 'Weeds'), ('Trees', 'Trees'), ('Toxic Plants', 'Toxic Plants')], max_length=100, null=True),
        ),
    ]
