# Generated by Django 4.2.11 on 2024-05-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_categoryplant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.categoryplant'),
        ),
        migrations.AddField(
            model_name='care_guide',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.categoryplant'),
        ),
        migrations.AddField(
            model_name='scientific_classification',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.categoryplant'),
        ),
    ]
