# Generated by Django 4.2.11 on 2024-05-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_attributes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants_types',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.categoryplant'),
        ),
    ]
