# Generated by Django 4.2.11 on 2024-05-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plants_types_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='toxicity',
        ),
    ]
